platform :ios, '11.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', 'Debug' => :debug, 'Profile' => :release, 'Release' => :release

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __dir__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure `flutter pub get` is executed first."
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    if line =~ /FLUTTER_ROOT=(.*)/
      return $1.strip
    end
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

flutter_root = flutter_root()
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper')

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
